/*function MASLogin(){
    it ('Login to MAS', function() {
            cy.visit('https://mas.brandpos.de/?signup')
            cy.get('footer').scrollIntoView()
            cy.contains('Already have account').click()
            cy.contains('Email or Username')
            //cy.get('#email').should('have.text', 'Enter your email or username')
            cy.get('#email').type('skmb1203@gmail.com', { delay: 50 })
            cy.contains('Password')
            cy.get('#password').type('BPOSMurali123#', { delay: 50 })
            cy.contains('Login').click()
            cy.get('.active > .nav-link > .nav-link-title')
                .should('be.visible')
                .log('Login is successful in MAS BrandPOS Portal')
        })
}

function MASLogout(){
    it ('Logout from MAS', function() {
            cy.get('.breadcrumb > :nth-child(1)').click()
            cy.get('.active > .nav-link > .nav-link-title').contains('Dashboard')
            cy.get('.top_header_container > .container-xl > .navbar-nav > .nav-item.dropdown > .nav-link').click()
            cy.get('#logout_me').click()
            cy.get('#auth_container > :nth-child(1) > img')
                .should('be.visible')
                .log('Logout is done successfully')
        })
}*/

describe('MAS BrandPOS Homepage', () => {
    beforeEach(() =>{
        cy.LoginMAS()
    })
    afterEach(() =>{
        cy.LogoutMAS()
    })
    it ('Check the main tabs', () => {
        //cy.LoginMAS()
        cy.get('#cookie-banner > .btn').click()
        cy.get('.active > .nav-link > .nav-link-title').contains('Dashboard')
        cy.get('.tour_connector_main_menu > .nav-link > .nav-link-title').contains('Connectors')
        cy.get(':nth-child(3) > .nav-link > .nav-link-title').contains('Search')
        cy.get(':nth-child(4) > .nav-link > .nav-link-title').contains('Finance')
        cy.get('.tour_settings_menu > .nav-link > .nav-link-title').contains('Settings')
        cy.get(':nth-child(6) > .nav-link > .nav-link-title').contains('Terminal')
        cy.get('.tour_store_main_menu > .nav-link > .nav-link-title').contains('Stores')
        //cy.LogoutMAS()
    })
    it ('Connector popup', () => {
        //cy.LoginMAS()
        cy.get('#cookie-banner > .btn').click()
        cy.get('.active > .nav-link > .nav-link-title').contains('Dashboard')
        cy.get('.tour_connector_main_menu > .nav-link > .nav-link-title')
          .contains('Connectors')
          .trigger('mouseover')
          .should('be.visible')
          .log('Popup of Connectors is listed successfully')
        cy.get('[href="/connectors/plugin/psp_connectors"]')
          .contains('PSP Connectors')
          .should('be.visible')
          .log('PSP Connectors is listed successfully')
        cy.get('[href="/connectors/plugin/pos_systems"]')
          .contains('POS Systems')
          .should('be.visible')
          .log('POS Systems is listed successfully')
        cy.get('[href="/connectors/plugin/direct_pay_types"]')
          .contains('Direct Pay Types')
          .should('be.visible')
          .log('Direct Pay Types is listed successfully')
        cy.get('[href="/connectors/plugin/accounting_systems"]')
          .contains('Accounting Systems')
          .should('be.visible')
          .log('Accounting Systems is listed successfully')
        cy.get('[href="/connectors/plugin/web_shops"]')
          .contains('Web Shops')
          .should('be.visible')
          .log('Web Shops is listed successfully')
        //cy.LogoutMAS()
    })
    it ('PSP Connector Page', () => {
        cy.get('#cookie-banner > .btn').click()
        cy.get('.active > .nav-link > .nav-link-title').contains('Dashboard')
        cy.get('.tour_connector_main_menu > .nav-link > .nav-link-title')
          .contains('Connectors')
          .trigger('mouseover')
          .should('be.visible')
          .log('Popup of Connectors is listed successfully')
        cy.get('[href="/connectors/plugin/psp_connectors"]').contains('PSP Connectors').click()
        cy.get('.active.cursor-pointer')
          .contains('PSP Connectors')
          .should('be.visible')
          .log('PSP Connector Page is opened successfully')
    })
    it ('POS Systems Page', () => {
        cy.get('#cookie-banner > .btn').click()
        cy.get('.active > .nav-link > .nav-link-title').contains('Dashboard')
        cy.get('.tour_connector_main_menu > .nav-link > .nav-link-title')
          .contains('Connectors')
          .trigger('mouseover')
          .should('be.visible')
          .log('Popup of Connectors is listed successfully')
        cy.get('[href="/connectors/plugin/pos_systems"]').contains('POS Systems').click()
        cy.get('.active.cursor-pointer')
          .contains('POS Systems')
          .should('be.visible')
          .log('POS Systems Page is opened successfully')
    })
    it ('Direct Pay Types Page', () => {
        cy.get('#cookie-banner > .btn').click()
        cy.get('.active > .nav-link > .nav-link-title').contains('Dashboard')
        cy.get('.tour_connector_main_menu > .nav-link > .nav-link-title')
          .contains('Connectors')
          .trigger('mouseover')
          .should('be.visible')
          .log('Popup of Connectors is listed successfully')
        cy.get('[href="/connectors/plugin/direct_pay_types"]').contains('Direct Pay Types').click()
        cy.get('.active.cursor-pointer')
          .contains('Direct Pay Types')
          .should('be.visible')
          .log('Direct Pay Types Page is opened successfully')
    })
    it ('Accounting Systems Page', () => {
        cy.get('#cookie-banner > .btn').click()
        cy.get('.active > .nav-link > .nav-link-title').contains('Dashboard')
        cy.get('.tour_connector_main_menu > .nav-link > .nav-link-title')
          .contains('Connectors')
          .trigger('mouseover')
          .should('be.visible')
          .log('Popup of Connectors is listed successfully')
        /*cy.get('[href="/connectors/plugin/accounting_systems"]').contains('Accounting Systems').click()
        cy.get('.active.cursor-pointer')
          .contains('Accounting Systems')
          .should('be.visible')
          .log('Accounting Systems Page is opened successfully')*/
    })
    it ('Web Shops Page', () => {
        cy.get('#cookie-banner > .btn').click()
        cy.get('.active > .nav-link > .nav-link-title').contains('Dashboard')
        cy.get('.tour_connector_main_menu > .nav-link > .nav-link-title')
          .contains('Connectors')
          .trigger('mouseover')
          .should('be.visible')
          .log('Popup of Connectors is listed successfully')
        cy.get('[href="/connectors/plugin/web_shops"]').contains('Web Shops').click()
        cy.get('.active.cursor-pointer')
          .contains('Web Shops')
          .should('be.visible')
          .log('Web Shops Page is opened successfully')
    })
})